version: '3.9'
services:
# -----------------------Servicio candidate -----------------------------
  
  app_candidate:
    build:
      context: .
      args:
        - VITE_HOLA=postgresql://postgres:postgres@db_candidate:5432/
        - VITE_API_CANDIDATE_LOCAL=http://localhost:3000/candidate
        - VITE_API_COMPANY_LOCAL=http://localhost:3001/company
        - VITE_API_PROJECTS_LOCAL=http://localhost:3007/projects
    ports:
      - "8080:8080"
    expose:
      - "8080"
#    volumes:
#      - ./:/usr/src/app
#      - exclude:/usr/src/app/node_modules
    restart: unless-stopped

volumes:
  exclude: