version: '3.9'
services:
# -----------------------Servicio candidate -----------------------------
  
  app_candidate:
    build:
      context: .
      args:
        - VITE_HOLA=postgresql://postgres:postgres@db_candidate:5432/
        - VITE_API_CANDIDATE=http://servicio-app-candidate/candidate    
        - VITE_API_COMPANY=http://servicio-app-company/company
        - VITE_API_COMPANY_EMPLOYEES=http://servicio-app-company-employees/company-employees
        - VITE_API_SEARCH=http://servicio-app-search-tool/search-tool
        - VITE_API_SELECTION_PROCESS=http://servicio-app-selection-procces/interviews
    ports:
      - "8080:8080"
    expose:
      - "8080"
#    volumes:
#      - ./:/usr/src/app
#      - exclude:/usr/src/app/node_modules
    restart: unless-stopped

volumes:
  exclude: