version: '3.9'
services:
# -----------------------Servicio candidate -----------------------------
  
  app_candidate:
    build:
      context: .
      args:
        - VITE_HOLA=postgresql://postgres:postgres@db_candidate:5432/
        - VITE_API_CANDIDATE=http://34.149.255.183/candidate    
        - VITE_API_COMPANY=http://34.149.255.183/company
        - VITE_API_COMPANY_EMPLOYEES=http://34.149.255.183/company-employees
        - VITE_API_PROJECTS=http://34.149.255.183/projects
        - VITE_API_SEARCH_TOOL=http://34.149.255.183/search-tool
        - VITE_API_SELECTION_PROCESS=http://34.149.255.183/interviews
    ports:
      - "8080:8080"
    expose:
      - "8080"
#    volumes:
#      - ./:/usr/src/app
#      - exclude:/usr/src/app/node_modules
    restart: unless-stopped

volumes:
  exclude: