version: '3.9'
services:
# -----------------------Servicio candidate -----------------------------
  
  app_candidate:
    build:
      context: .
      args:
        - VITE_HOLA=postgresql://postgres:postgres@db_candidate:5432/
        - VITE_API_CANDIDATE=API_CANDIDATE
        - VITE_API_COMPANY=API_COMPANY
        - VITE_API_PROJECTS=API_PROJECTS
    ports:
      - "8080:8080"
    expose:
      - "8080"
#    volumes:
#      - ./:/usr/src/app
#      - exclude:/usr/src/app/node_modules
    restart: unless-stopped

volumes:
  exclude: