name: App Web
run-name: ${{ github.actor }} is deploy App Web 🚀
on:
  push:
    branches: [feature/PROY**, fix/FIX**]
jobs:
  test-app-web:
    name: Correr-test
    if:  ${{ contains(github.event.head_commit.message, 'hecho') }}
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}

    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      # - name: run jest 
      #   run: npm run test

      - name: Validar resultado con errores
        if: ${{ failure() }}
        env:
          MENSAJE_ERROR: Una o varias pruebas fallaron
        run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        env:
          MENSAJE_EXITO: Todas las pruebas fueron exitosas
        run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"

  ci-app-web:
    name: Build and push to GCP
    needs: test-app-web
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:
    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
        IMAGE_NAME: front-app
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$GOOGLE_PROJECT/abc-jobs-dockers/$IMAGE_NAME:latest 
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$GOOGLE_PROJECT/abc-jobs-dockers/$IMAGE_NAME:$IMAGE_TAG 
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/abc-jobs-dockers/$IMAGE_NAME:latest 
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/abc-jobs-dockers/$IMAGE_NAME:$IMAGE_TAG 


  cd-app-candidate:
    name: Deploy to GCP k8s
    needs: [test-app-web, ci-app-web]
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}

    steps:

      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
        run: |
          cd deployment
          gcloud container clusters get-credentials autopilot-abc-jobs-k8s --region us-central1  --project $GOOGLE_PROJECT
          sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" k8s-web-deployment.yaml
          kubectl apply -f k8s-web-deployment.yaml
          kubectl rollout restart deployment/frontapp

  merge-branch-develop:
    name: Merge-dev
    needs: [test-app-web, ci-app-web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Branch name
        run: |
          echo running on branch ${GITHUB_REF##*/}
      - name: Mezcla ${GITHUB_REF##*/} -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: develop
          message: Merge ${GITHUB_REF##*/} into develop
          github_token: ${{ secrets.GITHUB_TOKEN }}